### ISSUE TITLE
Settings documentation

### ISSUE THREAD

**Issue by patillacode** [TerminalFi/LSP-copilot#110]
First of all, thanks for this, Sublime is kind of the forgotten editor these days. I was very glad to find this repo!

My issue:

I have unsuccessfully tried to find some documentation for the settings. 

I can see the default settings but I don't know what each one means and if I need to change it in my local or not.

For example, I know there is a `phantom` value allowed for the `completion_style` but just because I stumbled upon it by reading a closed issue.

What about the rest of options?
Is there any documentation I could read?

Cheers!

(Sorry if it exists and I missed it)

**Comment by jfcherng** [comment]
> Is there any documentation I could read?

In a hard way, yes, https://github.com/TerminalFi/LSP-copilot/blob/781b217d8de8cd32598d0e8f0be66a1773fe0850/sublime-package.json#L52-L60.

In the easy way, install LSP-json.
![image](https://github.com/TerminalFi/LSP-copilot/assets/6594915/18b0b962-5146-4f03-9615-f41f6e1e36ab)

**Comment by patillacode** [comment]
> In the hard way, yes,
oh, wow! this is something! thanks!

Regarding your last image, I have LSP-json installed although I don't get what you get... do you have any clue as to why?
My LSP-json settings are empty, meaning I am using the default ones, are you?

**Comment by patillacode** [comment]
Forgot to put the images:

![Screenshot 2023-06-01 at 12 49 12](https://github.com/TerminalFi/LSP-copilot/assets/10074977/15c2570e-5e46-40fc-b966-71509fc763d4)
![Screenshot 2023-06-01 at 12 56 52](https://github.com/TerminalFi/LSP-copilot/assets/10074977/fbae7efe-6645-4de9-b4dc-31ab58f9bedd)

**Comment by jfcherng** [comment]
> > In the hard way, yes,
> > oh, wow! this is something! thanks!
> 
> Regarding your last image, I have LSP-json installed although I don't get what you get... do you have any clue as to why? My LSP-json settings are empty, meaning I am using the default ones, are you?

First check LSP-json is activated, see the bottom-left corner just like you can see LSP-copilot there.

**Comment by patillacode** [comment]
![Screenshot 2023-06-01 at 13 05 17](https://github.com/TerminalFi/LSP-copilot/assets/10074977/81e6bd37-d674-4b5d-9017-ed1b7d3e5daa)

it looks like it is up and running...

**Comment by patillacode** [comment]
I don't know what it is, if it works for you it should for me too.
My Sublime installation is pretty minimal, LSP and only a couple more packages are installed, so I am pretty sure there are no conflicts, maybe I need to set some settings in LSP-json or in the generic ST settings?

Also I notices in your image you get copilot in the settings file but I don't 😅

**Comment by jfcherng** [comment]
> maybe I need to set some settings in LSP-json or in the generic ST settings?

No. It should just work.

**Comment by jfcherng** [comment]
What if you trigger auto completion manually?

**Comment by rwols** [comment]
It seems to be stuck initializating.

**Comment by patillacode** [comment]
Cannot trigger it manually, it doesn't appear as an option when in the settings file!

Good call about the console:

LSP log is empty

ST console isn't:
```
Unable to open /Users/dvitto/Library/Application Support/Sublime Text/Packages/LSP-copilot/LSP-copilot.sublime-settings
Error handling None
Traceback (most recent call last):
  File "/Users/dvitto/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 2077, in on_payload
    handler(result)
  File "/Users/dvitto/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 1427, in _handle_initialize_success
    self._plugin = self._plugin_class(weakref.ref(self))
  File "/Users/dvitto/Library/Application Support/Sublime Text/Installed Packages/LSP-json.sublime-package/plugin.py", line 46, in __init__
  File "/Users/dvitto/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/generic_client_handler.py", line 187, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dvitto/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 157, in __init__
    self.on_ready(api)
  File "/Users/dvitto/Library/Application Support/Sublime Text/Installed Packages/LSP-json.sublime-package/plugin.py", line 61, in on_ready
  File "/Users/dvitto/Library/Application Support/Sublime Text/Installed Packages/LSP-json.sublime-package/schema_store.py", line 53, in load_schemas_async
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

Maybe you are more versed on this, I am not sure I understand the issue 🤔

**Comment by jfcherng** [comment]
Does the error persist even after restarting ST?

**Comment by patillacode** [comment]
Legend, restarting worked....

![Screenshot 2023-06-01 at 13 57 34](https://github.com/TerminalFi/LSP-copilot/assets/10074977/15dc839a-af94-40bf-9c52-961b6a5429c0)


I am happy it works but it bugs me hard at the same time!

**Comment by patillacode** [comment]
We ended up talking about something totally different from the original matter, thanks for following me to the side-track! 

I think we can close this?
