### ISSUE TITLE
"KeyError" when using phantom

### ISSUE THREAD

**Issue by WangWei90** [TerminalFi/LSP-copilot#153]
Thanks for this plugin~ it is very useful~

When I start sublime, open a file, and the following error occurs.
```
✈ Copilot has been signed in and authorized.
Traceback (most recent call last):
  File "C:\zone1a\tool1a\text-sublime4x64\Lib\python38\sublime_plugin.py", line 922, in on_close
    run_view_callbacks('on_close', view_id)
  File "C:\zone1a\tool1a\text-sublime4x64\Lib\python38\sublime_plugin.py", line 747, in run_view_callbacks
    callback(*args)
  File "C:\zone1a\tool1a\text-sublime4x64\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\zone1a\tool1a\text-sublime4x64\Data\Installed Packages\LSP-copilot.sublime-package\plugin/listeners.py", line 76, in on_close
    ViewCompletionManager(self.view).handle_close()
  File "C:\zone1a\tool1a\text-sublime4x64\Data\Installed Packages\LSP-copilot.sublime-package\plugin/ui/completion.py", line 131, in handle_close
    self.completion_style_type.close(self.view)
  File "C:\zone1a\tool1a\text-sublime4x64\Data\Installed Packages\LSP-copilot.sublime-package\plugin/ui/completion.py", line 449, in close
    del _view_to_phantom_set[view.id()]
KeyError: 192
```

**Comment by timfjord** [comment]
You can ignore this error, as it doesn't affect the functionality.
The cache(`_view_to_phantom_set `) sometimes goes out of sync, thus the error.
