### ISSUE TITLE
No module named 'more_itertools' since reinstalling LSP-copilot plugin

### ISSUE THREAD

**Issue by wdhow** [TerminalFi/LSP-copilot#161]
The plugin was working seamlessly for a month prior to reinstall. Thanks for an amazing tool. I've had problems recently upon reinstalling LSP-copilot, or restarting Sublime Text 4. I am getting the following error in the ST4 console:

```
reloading plugin LSP-copilot.boot
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\walte\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\boot.py", line 15, in <module>
  File "C:\Users\walte\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/__init__.py", line 3, in <module>
  File "C:\Users\walte\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/commands.py", line 27, in <module>
  File "C:\Users\walte\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/plugin.py", line 40, in <module>
  File "C:\Users\walte\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/ui/__init__.py", line 3, in <module>
  File "C:\Users\walte\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/ui/completion.py", line 10, in <module>
ModuleNotFoundError: No module named 'more_itertools'

...

Package Control: Error downloading channel. Operation timed out (errno 12002) during HTTP write phase of downloading https://packagecontrol.github.io/channel/channel_v4.json.
Package Control: The library "more-itertools" is not available for Python 3.8
Package Control: Skipping automatic upgrade, last run at 2024-06-03 22:53:22, next run at 2024-06-04 06:53:22 or after

```

I'm on a Win 11 box, and athough LSP-copilot ran fine without a defined system Python install, I have tried adding installing Python alongside `more_itertools` and adding to PATH, although this doesn't work.

**Comment by TerminalFi** [comment]
Can you try restarting sublime? Also try upgrading package control

**Comment by jfcherng** [comment]
> Package Control: Error downloading channel. Operation timed out (errno 12002) during HTTP write phase of downloading https://packagecontrol.github.io/channel/channel_v4.json.

It looks like you are having an issue in accessing GitHub?

**Comment by wdhow** [comment]
@jfcherng, @TerminalFi I restarted ST4 several times when I had this problem yesterday evening to no avail, and did not get the chance to reinstall Package Control at the time.

This evening it seems ST4 automatically installed a new version of Package Control and everything is now working! So I suppose the issue was with Package Control all along.

Sorry for stringing you along, and thank you for your time.
