### ISSUE TITLE
Error: No instance of WorkspaceWatcherProvider has been registered

### ISSUE THREAD

**Issue by bhavanki** [TerminalFi/LSP-copilot#170]
I've started seeing this error in the past week. I was able to get it to stop previously by ensuring no other `node` was in the path and by reinstalling the package, but it's come back.

```
LSP: Resolved Node.js Runtime for package LSP-copilot: NodeRuntimeLocal(node: /Users/bhavanki/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/18.18.1/node/bin/node, npm: /Users/bhavanki/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/18.18.1/node/lib/node_modules/npm/bin/npm-cli.js, version: 18.18.1)
LSP: starting ['/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/18.18.1/node/bin/node', '/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js', '--stdio'] in /Users/bhavanki/dev/src/github.com/segmentio/devme
LSP-copilot: ERROR: [default] unhandledRejection: Error: No instance of WorkspaceWatcherProvider has been registered.
    at sW.get (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:219:32111)
    at hX.onWorkspacesAdded (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:368:3945)
    at EventEmitter.<anonymous> (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:368:3750)
    at EventEmitter.emit (node:events:517:28)
    at wK.emit (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:288:1808)
    at /Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:940:91566
    at /Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:39:82220
    at handleRequest (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:9:9296)
    at handleMessage (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:9:6762)
    at processMessageQueue (/Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot/18.18.1/language-server/node_modules/copilot-node-server/copilot/dist/language-server.js:9:6994)
```

* Sublime Text Build 4169
* macOS Sonoma 14.5

**Comment by jfcherng** [comment]
Can you try to delete both 

- /Users/bhavanki/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime
- /Users/bhavanki/Library/Caches/Sublime Text/Package Storage/LSP-copilot

and restart ST? If ST ask you to install `node`, click yes/ok or something like that.

**Comment by TerminalFi** [comment]
Seeing as this has had no follow up, I am going to be closing this out. 

Please re-open if you are still running into this issue.
