### ISSUE TITLE
Chat disappears

### ISSUE THREAD

**Issue by unknownuser88** [TerminalFi/LSP-copilot#206]
chat tab disappears at a random moment

I have following error in console

`AttributeError: 'NoneType' object has no attribute 'scope_name'
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1329, in is_enabled_
    ret = self.is_enabled()
  File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 182, in is_enabled
    return self.is_relevant_file()
  File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 178, in is_relevant_file
    return sublime.active_window().active_view().scope_name(
AttributeError: 'NoneType' object has no attribute 'scope_name'
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1329, in is_enabled_
    ret = self.is_enabled()
  File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 182, in is_enabled
    return self.is_relevant_file()
  File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 178, in is_relevant_file
    return sublime.active_window().active_view().scope_name(
AttributeError: 'NoneType' object has no attribute 'scope_name'
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1329, in is_enabled_
    ret = self.is_enabled()
  File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 182, in is_enabled
    return self.is_relevant_file()
  File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 178, in is_relevant_file
    return sublime.active_window().active_view().scope_name(
AttributeError: 'NoneType' object has no attribute 'scope_name'
SublimeLinter: sublime_linter.py:334  Delay linting '<untitled 466>' for 0.0s
SublimeLinter: sublime_linter.py:352  No installed linter matches the view.`

sublime build 4180
Ubuntu 20.04.6 LTS

**Comment by jfcherng** [comment]
The error msg doesn't seem to related to this plugin. It suggests `sublime.active_window().active_view()` is `None` however.

**Comment by TerminalFi** [comment]
Nothing here seems related to LSP-copilot. But rather NodeJS package and SublimeLinter

```
AttributeError: 'NoneType' object has no attribute 'scope_name' Traceback (most recent call last): 
	File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1329, in is_enabled_ ret = self.is_enabled() 
	File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 182, in is_enabled return self.is_relevant_file() 
	File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 178, in is_relevant_file return sublime.active_window().active_view().scope_name( AttributeError: 'NoneType' object has no attribute 'scope_name' Traceback (most recent call last): 
		File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1329, in is_enabled_ ret = self.is_enabled() 
		File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 182, in is_enabled return self.is_relevant_file() 
		File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 178, in is_relevant_file return sublime.active_window().active_view().scope_name( AttributeError: 'NoneType' object has no attribute 'scope_name' Traceback (most recent call last): 
			File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1329, in is_enabled_ ret = self.is_enabled() File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 182, in is_enabled return self.is_relevant_file() 
			File "/home/david/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 178, in is_relevant_file return sublime.active_window().active_view().scope_name( AttributeError: 'NoneType' object has no attribute 'scope_name' SublimeLinter: sublime_linter.py:334  
	Delay linting '<untitled 466>' for 0.0s SublimeLinter: sublime_linter.py:352  No installed linter matches the view.
```
