### ISSUE TITLE
LSP Copilot chat, stops working

### ISSUE THREAD

**Issue by DJManas** [TerminalFi/LSP-copilot#220]
Hello,

today I used LSP copilot for working and after some time, it stopped working. I use ctrl + shift + p, copilot chat, enter question and nothing generates.

In console I see:
```
Traceback (most recent call last):
  File "/home/djmanas/.config/sublime-text/Packages/LSP-copilot/plugin/commands.py", line 250, in <lambda>
    wcm.prompt(callback=lambda msg: self._on_prompt(plugin, session, msg), initial_text=message)
  File "/home/djmanas/.config/sublime-text/Packages/LSP-copilot/plugin/commands.py", line 335, in _on_prompt
    if not (request := prepare_conversation_turn_request(wcm.conversation_id, wcm.window.id(), msg, view, views)):
  File "/home/djmanas/.config/sublime-text/Packages/LSP-copilot/plugin/helpers.py", line 234, in prepare_conversation_turn_request
    if not (selection := view_.sel()[0]) or view_.substr(selection).isspace():
  File "/opt/sublime_text/Lib/python38/sublime.py", line 2291, in __getitem__
    raise IndexError()
IndexError
```

Sublime-Text: 4_4184 (Yes it dev so I dunno if it should not go to them)
Gentoo Linux

Thanks,
Regards,
Petr Sourek

**Comment by TerminalFi** [comment]
TODO: Fix line https://github.com/TerminalFi/LSP-copilot/blob/a0c75e065e362bfbb000d9b4a2c68ceb31c94c8b/plugin/helpers.py#L234

**Comment by jfcherng** [comment]
> TODO: Fix line

So there is either no cursor (which is supposed not to happen) or `view_` is wrong 🤔

**Comment by DJManas** [comment]
If you can point me to what I should look for, I will be able to test it next time it happens.

**Comment by DJManas** [comment]
> Reproduceable steps would help if it's possible.

I would try, but the problem is, that I had been developing python script since morning and suddenly when I got back with cup of coffee the Copilot was not responding and error was in console. We will see if it happens tonight or tomorrow during the day.

**Comment by jfcherng** [comment]
> > Reproduceable steps would help if it's possible.
> 
> I will try, but the problem is, that I had been developing python script since morning and suddenly when I got back with cup of coffee the Copilot was not responding and error was in console. We will see if it happens tonight or tomorrow during the day.

I see. Sometimes it's just hard to find a stable way to reproduce a bug.

**Comment by TerminalFi** [comment]
@DJManas i am seeing this now as well. I hope to have time this weekend to review both our code and any changes that may have occurred in the upstream copilot.vim that we may have missed

**Comment by TerminalFi** [comment]
@jfcherng 

Looks like something changed, and when creating a new conversation and sending an empty turn message. It doesn't like it. We should try and not send an empty message when creating a conversation now

**Comment by TerminalFi** [comment]
> @jfcherng
> 
> Looks like something changed, and when creating a new conversation and sending an empty turn message. It doesn't like it. We should try and not send an empty message when creating a conversation now

Initial message here can be blank https://github.com/TerminalFi/LSP-copilot/blob/530359c6184592c77cb1f996a1b6eeb32430fa44/plugin/commands.py#L276

So maybe we need a way to send a message `Hello` if this is a brand new conversation? Or postpone this until user provides first message?

**Comment by jfcherng** [comment]
I am not sure what's happening since copilot chat seems to just work on my side.

**Comment by StephenKercherPP** [comment]
right after i submitted that message, i tried again and it worked this time.
I realized i was attempting to reference temporary code (not code saved in a file).
Turns out that the plugin does not reference code from the editor; it references code from the file (which is open in the editor).

**The plugin cannot reference unsaved code (code which only exists in the editor, but not in a file)**
Is this correct?

**Comment by jfcherng** [comment]
> right after i submitted that message, i tried again and it worked this time. I realized i was attempting to reference temporary code (not code saved in a file). Turns out that the plugin does not reference code from the editor; it references code from the file (which is open in the editor).
> 
> **The plugin cannot reference unsaved code (code which only exists in the editor, but not in a file)** Is this correct?

On my side, if you select those codes, it works.

**Comment by StephenKercherPP** [comment]
strange.
I highlight code, run the "Copilot: Chat" command, and the window remains blank.
This problem only happens with code that is unsaved.

![Image](https://github.com/user-attachments/assets/7fb96868-ae30-48f2-96df-eb5817e017b1)

**Comment by DJManas** [comment]
> **The plugin cannot reference unsaved code (code which only exists in the editor, but not in a file)** Is this correct?

I agree that this might be problem, but in my first post I didn't referenced anything, still learning how to use Copilot so most of my prompts are mostly questions, not referencing my code.

**Comment by TerminalFi** [comment]
Just confirming I am able to reproduce this issue. I am looking into it.

**Comment by TerminalFi** [comment]
I've identified the issue. This line below fails if the view does not have a file on disk.

https://github.com/TerminalFi/LSP-copilot/blob/530359c6184592c77cb1f996a1b6eeb32430fa44/plugin/helpers.py#L199

I will try to find time today to fix this.

**Comment by StephenKercherPP** [comment]
> today I used LSP copilot for working and after some time, it stopped working. I use ctrl + shift + p, copilot chat, enter question and nothing generates.

I misunderstood your original question then;  sorry for hijacking the thread!
I agree with @TerminalFi for the reason why.
An invalid "hello" message could corrupt future questions for that session.

@DJManas are you able to find steps that let you use CoPilot again?  (e.g. Close and Reopen Sublime | Sign Out -> Sign back in to CoPilot | Copilot: Destroy Conversation | Remove package then re-add package)?  Or is it permanently broken right now?

**Comment by TerminalFi** [comment]
> > today I used LSP copilot for working and after some time, it stopped working. I use ctrl + shift + p, copilot chat, enter question and nothing generates.
> 
> I misunderstood your original question then;  sorry for hijacking the thread!
> I agree with @TerminalFi for the reason why.
> An invalid "hello" message could corrupt future questions for that session.
> 
> @DJManas are you able to find steps that let you use CoPilot again?  (e.g. Close and Reopen Sublime | Sign Out -> Sign back in to CoPilot | Copilot: Destroy Conversation | Remove package then re-add package)?  Or is it permanently broken right now?

It will work on files that are actually saved to disk currently. 

We think we also found a bug in LSP for unsaved views.

**Comment by DJManas** [comment]
> > today I used LSP copilot for working and after some time, it stopped working. I use ctrl + shift + p, copilot chat, enter question and nothing generates.
> 
> I misunderstood your original question then; sorry for hijacking the thread! I agree with [@TerminalFi](https://github.com/TerminalFi) for the reason why. An invalid "hello" message could corrupt future questions for that session.
> 
> [@DJManas](https://github.com/DJManas) are you able to find steps that let you use CoPilot again? (e.g. Close and Reopen Sublime | Sign Out -> Sign back in to CoPilot | Copilot: Destroy Conversation | Remove package then re-add package)? Or is it permanently broken right now?

Seems that copilot is working today, I will continue to use it. As stated in my first comment. I have problems, that it stops working after some time (not sure why), but before it its working normally (talking about chat).

And I had written, that I am not using it on unsaved files, but in the same sentence I had written, that its good point. Now thinking about it, and working, when I see there is problem (in source) I will save first and try again. I guess this is thing, that would not get into my mind, when I have problems in source code usage.

**Comment by jfcherng** [comment]
> I've identified the issue. This line below fails if the view does not have a file on disk.
> 
> [LSP-copilot/plugin/helpers.py](https://github.com/TerminalFi/LSP-copilot/blob/530359c6184592c77cb1f996a1b6eeb32430fa44/plugin/helpers.py#L199)
> 
> Line 199 in [530359c](/TerminalFi/LSP-copilot/commit/530359c6184592c77cb1f996a1b6eeb32430fa44)
> 
>  if not view.file_name(): 
> I will try to find time today to fix this.

I have fixed and pushed that line. But another issue related to LSP (wrong buffer ID in payloads) is still required to be addressed.
