### ISSUE TITLE
LSP Copilot stopped working

### ISSUE THREAD

**Issue by Blindmikey** [TerminalFi/LSP-copilot#222]
Only when LSP-Copilot Package is enabled, do I see this error:

```
reloading plugin LSP-copilot.boot
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\[...]\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\boot.py", line 15, in <module>
  File "C:\Users\[...]\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/__init__.py", line 3, in <module>
  File "C:\Users\[...]\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/client.py", line 32, in <module>
  File "C:\Users\[...]\AppData\Roaming\Sublime Text\Installed Packages\LSP-copilot.sublime-package\plugin/helpers.py", line 12, in <module>
  File "C:\Users\[...]\AppData\Roaming\Sublime Text\Lib\python38\requests\__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

No LSP status in lower-left. 
No "Copilot: sign in" option available. 

Any guidance is appreciated.

**Comment by Blindmikey** [comment]
Reverting this commit fixed the issue:
https://github.com/TerminalFi/LSP-copilot/commit/3f890e9614b07638f6f861b1e9d72105a7cc58f4

**Comment by jfcherng** [comment]
Sorry about this. `v0.3.4` has been tagged and will be available within hours.
