### ISSUE TITLE
Stops working after last update 12 Dic

### ISSUE THREAD

**Issue by frives-w** [TerminalFi/LSP-copilot#223]
The plugin was working perfectly, but today it was updated and it stopped working.
The console show:

reloading plugin LSP-copilot.boot
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fran/.config/sublime-text-3/Installed Packages/LSP-copilot.sublime-package/boot.py", line 15, in <module>
  File "/home/fran/.config/sublime-text-3/Installed Packages/LSP-copilot.sublime-package/plugin/__init__.py", line 3, in <module>
  File "/home/fran/.config/sublime-text-3/Installed Packages/LSP-copilot.sublime-package/plugin/client.py", line 32, in <module>
  File "/home/fran/.config/sublime-text-3/Installed Packages/LSP-copilot.sublime-package/plugin/helpers.py", line 12, in <module>
  File "/home/fran/.config/sublime-text-3/Lib/python38/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'_

Any suggestions for solving the problem?
Thanks

**Comment by jfcherng** [comment]
https://github.com/TerminalFi/LSP-copilot/issues/222

**Comment by frives-w** [comment]
Thank you very much! The work you are doing is amazing.
