### ISSUE TITLE
Failed to start LSP-copilot - disabling for this window for the duration of the current session. Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.

### ISSUE THREAD

**Issue by witcan** [TerminalFi/LSP-copilot#64]
![image](https://user-images.githubusercontent.com/48895485/198953544-6b0003e7-6c78-42e7-9548-164159ceda4b.png)

```
startup, version: 4126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/aiyuhang/Library/Application Support/Sublime Text/Packages
state path: /Users/aiyuhang/Library/Application Support/Sublime Text/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/aiyuhang/Library/Application Support/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.28513
font face "Consolas" could not be found, defaulting to "Menlo"
OpenGL Context Information:
  GL API Version: 4.1 ATI-4.8.101
  GLSL Version: 4.10
  Vendor: ATI Technologies Inc.
  Renderer: AMD Radeon Pro 5500M OpenGL Engine
startup time: 0.396279
first paint time: 0.512784
git: located Sublime Merge installed at /Applications/Sublime Merge.app
git: using configuration from system git install
git: tracking working dir /Users/aiyuhang/gitee/gitee
git: tracking working dir /Users/aiyuhang/gitee/gitee/tmp/tests/gitlab-test
git: tracking working dir /Users/aiyuhang/gitee/gitee/tmp/tests/gitlab-test-fork
git: tracking working dir /Users/aiyuhang/gitee/gitee/tmp/tests/gitlab-test-wiki
git: tracking working dir /Users/aiyuhang/gitee/gitee/tmp/tests/gitaly
environment variables loaded using: /bin/zsh -l
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading plugin Default.arithmetic
reloading python 3.3 plugin 0_package_control_loader.01-sublime_lib
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading python 3.3 plugin 0_package_control_loader.10-lsp_utils
reloading python 3.3 plugin 0_package_control_loader.50-backrefs
reloading python 3.3 plugin 0_package_control_loader.50-bracex
reloading python 3.3 plugin 0_package_control_loader.50-pathlib
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
reloading plugin Default.colors
reloading python 3.3 plugin 0_package_control_loader.55-wcmatch
reloading python 3.3 plugin ayu.activation
reloading python 3.3 plugin ayu.Icons
reloading python 3.3 plugin Git.git_commands
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading python 3.3 plugin LSP-copilot.boot
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
git: tracking working dir /Users/aiyuhang/gitee/gitee/tmp/tests/gitaly/_build/deps/libgit2/source
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading python 3.3 plugin LSP.boot
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin Terminal.Terminal
plugins loaded
[lsp_utils] START output of command: "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.jsci--scripts-prepend-node-path=true--verbose--production"

[lsp_utils] Command output END
Unable to start subprocess for LSP-copilot
Traceback (most recent call last):
  File "/Users/aiyuhang/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 107, in install_or_update
    self._node_runtime.npm_install(self._server_dest)
  File "/Users/aiyuhang/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/node_runtime.py", line 180, in npm_install
    raise Exception('Failed to run npm command "{}":\n{}'.format(' '.join(args), error))
Exception: Failed to run npm command "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.js ci --scripts-prepend-node-path=true --verbose --production":
npm verb cli [
npm verb cli   '/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node',
npm verb cli   '/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.js',
npm verb cli   'ci',
npm verb cli   '--scripts-prepend-node-path=true',
npm verb cli   '--verbose',
npm verb cli   '--production'
npm verb cli ]
npm info using npm@8.5.5
npm info using node@v16.15.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm verb config production Use `--omit=dev` instead.
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/LSP-copilot/16.15.0/language-server/.npmrc Completed in 0ms
npm timing config:load:project Completed in 7ms
npm timing config:load:file:/Users/aiyuhang/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 15ms
npm timing npm:load:configload Completed in 15ms
npm timing npm:load:setTitle Completed in 15ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 5ms
npm verb logfile /Users/aiyuhang/.npm/_logs/2022-10-31T07_18_45_961Z-debug-0.log
npm timing npm:load:logFile Completed in 4ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 41ms
npm timing arborist:ctor Completed in 1ms
npm timing npm-ci:rm Completed in 3ms
npm timing idealTree:init Completed in 1ms
npm timing idealTree:userRequests Completed in 0ms
npm timing idealTree:#root Completed in 0ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 4ms
npm timing reify:loadTrees Completed in 2ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 1ms
npm timing reify:trashOmits Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 242ms (cache skip)
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 57ms (cache skip)
npm verb audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
npm verb audit error     at /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:336:21)
npm verb audit error     at async Map.run (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19)
npm verb audit error  HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
npm verb audit error     at /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:336:21)
npm verb audit error     at async Map.run (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
npm verb audit error   headers: [Object: null prototype] {
npm verb audit error     server: [ 'Tengine' ],
npm verb audit error     'content-type': [ 'text/html; charset=utf-8' ],
npm verb audit error     'content-length': [ '41' ],
npm verb audit error     connection: [ 'keep-alive' ],
npm verb audit error     'strict-transport-security': [ 'max-age=5184000' ],
npm verb audit error     date: [ 'Mon, 31 Oct 2022 07:18:46 GMT' ],
npm verb audit error     vary: [ 'Origin' ],
npm verb audit error     'x-frame-options': [ 'SAMEORIGIN' ],
npm verb audit error     'x-xss-protection': [ '1; mode=block' ],
npm verb audit error     'x-content-type-options': [ 'nosniff' ],
npm verb audit error     'x-download-options': [ 'noopen' ],
npm verb audit error     'x-readtime': [ '2.474' ],
npm verb audit error     'content-encoding': [ 'gzip' ],
npm verb audit error     'ali-swift-global-savetime': [ '1667200726' ],
npm verb audit error     via: [
npm verb audit error       'cache15.l2cn1851[39,39,404-1280,M], cache57.l2cn1851[40,0], kunlun3.cn1427[0,0,404-0,H], kunlun10.cn1427[1,0]'
npm verb audit error     ],
npm verb audit error     age: [ '0' ],
npm verb audit error     'x-cache': [ 'HIT TCP_MEM_HIT dirn:-2:-2' ],
npm verb audit error     'x-swift-savetime': [ 'Mon, 31 Oct 2022 07:18:46 GMT' ],
npm verb audit error     'x-swift-cachetime': [ '1' ],
npm verb audit error     'timing-allow-origin': [ '*' ],
npm verb audit error     eagleid: [ '6f7b311e16672007267407022e' ],
npm verb audit error     'x-fetch-attempts': [ '1' ],
npm verb audit error     'x-local-cache-status': [ 'skip' ]
npm verb audit error   },
npm verb audit error   statusCode: 404,
npm verb audit error   code: 'E404',
npm verb audit error   method: 'POST',
npm verb audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
npm verb audit error   body: <Buffer 3c 68 31 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 68 31 3e>,
npm verb audit error   pkgid: undefined
npm verb audit error }
npm timing auditReport:getReport Completed in 308ms
npm timing reify:audit Completed in 308ms
npm http fetch GET 404 https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz 392ms (cache skip)
npm timing reify:rollback:createSparse Completed in 2ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:ci Completed in 453ms
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz
npm verb stack     at /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb statusCode 404
npm verb pkgid copilot-node-server@https://registry.npm.taobao.org/copilot-node-server/-/copilot-node-server-1.6.0.tgz
npm verb cwd /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/LSP-copilot/16.15.0/language-server
npm verb Darwin 21.6.0
npm verb argv "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node" "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.js" "ci" "--scripts-prepend-node-path=true" "--verbose" "--production"
npm verb node v16.15.0
npm verb npm  v8.5.5
npm ERR! code E404
npm ERR! 404 Not Found - GET https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz
npm ERR! 404 
npm ERR! 404  'copilot-node-server@https://registry.npm.taobao.org/copilot-node-server/-/copilot-node-server-1.6.0.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm timing npm Completed in 757ms
npm verb unfinished npm timer reify 1667200726279
npm verb unfinished npm timer reify:unpack 1667200726291
npm verb unfinished npm timer reifyNode:node_modules/copilot-node-server 1667200726291
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiyuhang/.npm/_logs/2022-10-31T07_18_45_961Z-debug-0.log

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aiyuhang/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 253, in start_async
    plugin_class.install_or_update()
  File "/Users/aiyuhang/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 109, in install_or_update
    server.install_or_update()
  File "/Users/aiyuhang/Library/Application Support/Sublime Text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 111, in install_or_update
    raise Exception('Error installing the server:\n{}'.format(error))
Exception: Error installing the server:
Failed to run npm command "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.js ci --scripts-prepend-node-path=true --verbose --production":
npm verb cli [
npm verb cli   '/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node',
npm verb cli   '/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.js',
npm verb cli   'ci',
npm verb cli   '--scripts-prepend-node-path=true',
npm verb cli   '--verbose',
npm verb cli   '--production'
npm verb cli ]
npm info using npm@8.5.5
npm info using node@v16.15.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm verb config production Use `--omit=dev` instead.
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/LSP-copilot/16.15.0/language-server/.npmrc Completed in 0ms
npm timing config:load:project Completed in 7ms
npm timing config:load:file:/Users/aiyuhang/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 15ms
npm timing npm:load:configload Completed in 15ms
npm timing npm:load:setTitle Completed in 15ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 5ms
npm verb logfile /Users/aiyuhang/.npm/_logs/2022-10-31T07_18_45_961Z-debug-0.log
npm timing npm:load:logFile Completed in 4ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 41ms
npm timing arborist:ctor Completed in 1ms
npm timing npm-ci:rm Completed in 3ms
npm timing idealTree:init Completed in 1ms
npm timing idealTree:userRequests Completed in 0ms
npm timing idealTree:#root Completed in 0ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 4ms
npm timing reify:loadTrees Completed in 2ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 1ms
npm timing reify:trashOmits Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 242ms (cache skip)
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 57ms (cache skip)
npm verb audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
npm verb audit error     at /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:336:21)
npm verb audit error     at async Map.run (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19)
npm verb audit error  HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
npm verb audit error     at /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:336:21)
npm verb audit error     at async Map.run (/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
npm verb audit error   headers: [Object: null prototype] {
npm verb audit error     server: [ 'Tengine' ],
npm verb audit error     'content-type': [ 'text/html; charset=utf-8' ],
npm verb audit error     'content-length': [ '41' ],
npm verb audit error     connection: [ 'keep-alive' ],
npm verb audit error     'strict-transport-security': [ 'max-age=5184000' ],
npm verb audit error     date: [ 'Mon, 31 Oct 2022 07:18:46 GMT' ],
npm verb audit error     vary: [ 'Origin' ],
npm verb audit error     'x-frame-options': [ 'SAMEORIGIN' ],
npm verb audit error     'x-xss-protection': [ '1; mode=block' ],
npm verb audit error     'x-content-type-options': [ 'nosniff' ],
npm verb audit error     'x-download-options': [ 'noopen' ],
npm verb audit error     'x-readtime': [ '2.474' ],
npm verb audit error     'content-encoding': [ 'gzip' ],
npm verb audit error     'ali-swift-global-savetime': [ '1667200726' ],
npm verb audit error     via: [
npm verb audit error       'cache15.l2cn1851[39,39,404-1280,M], cache57.l2cn1851[40,0], kunlun3.cn1427[0,0,404-0,H], kunlun10.cn1427[1,0]'
npm verb audit error     ],
npm verb audit error     age: [ '0' ],
npm verb audit error     'x-cache': [ 'HIT TCP_MEM_HIT dirn:-2:-2' ],
npm verb audit error     'x-swift-savetime': [ 'Mon, 31 Oct 2022 07:18:46 GMT' ],
npm verb audit error     'x-swift-cachetime': [ '1' ],
npm verb audit error     'timing-allow-origin': [ '*' ],
npm verb audit error     eagleid: [ '6f7b311e16672007267407022e' ],
npm verb audit error     'x-fetch-attempts': [ '1' ],
npm verb audit error     'x-local-cache-status': [ 'skip' ]
npm verb audit error   },
npm verb audit error   statusCode: 404,
npm verb audit error   code: 'E404',
npm verb audit error   method: 'POST',
npm verb audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
npm verb audit error   body: <Buffer 3c 68 31 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 68 31 3e>,
npm verb audit error   pkgid: undefined
npm verb audit error }
npm timing auditReport:getReport Completed in 308ms
npm timing reify:audit Completed in 308ms
npm http fetch GET 404 https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz 392ms (cache skip)
npm timing reify:rollback:createSparse Completed in 2ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:ci Completed in 453ms
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz
npm verb stack     at /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb statusCode 404
npm verb pkgid copilot-node-server@https://registry.npm.taobao.org/copilot-node-server/-/copilot-node-server-1.6.0.tgz
npm verb cwd /Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/LSP-copilot/16.15.0/language-server
npm verb Darwin 21.6.0
npm verb argv "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node" "/Users/aiyuhang/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/lib/node_modules/npm/bin/npm-cli.js" "ci" "--scripts-prepend-node-path=true" "--verbose" "--production"
npm verb node v16.15.0
npm verb npm  v8.5.5
npm ERR! code E404
npm ERR! 404 Not Found - GET https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz
npm ERR! 404 
npm ERR! 404  'copilot-node-server@https://registry.npm.taobao.org/copilot-node-server/-/copilot-node-server-1.6.0.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm timing npm Completed in 757ms
npm verb unfinished npm timer reify 1667200726279
npm verb unfinished npm timer reify:unpack 1667200726291
npm verb unfinished npm timer reifyNode:node_modules/copilot-node-server 1667200726291
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiyuhang/.npm/_logs/2022-10-31T07_18_45_961Z-debug-0.log

Package Control: Skipping automatic upgrade, last run at 2022-10-31 15:11:58, next run at 2022-10-31 16:11:58 or after
```
my lsp_untils
![image](https://user-images.githubusercontent.com/48895485/198953689-d54bc967-afbd-4568-8b04-ba19b39e408f.png)

**Comment by jfcherng** [comment]
It looks like the NPM mirror you used is not up-to-date so `copilot-node-server-1.6.0` is not found.

- https://registry.npm.taobao.org/copilot-node-server/-/copilot-node-server-1.6.0.tgz
- https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz

**Comment by jfcherng** [comment]
I think except that change to another mirror, the only workaround is probably to overwrite the `language-server` directory with a previous version's.

https://github.com/TerminalFi/LSP-copilot/tree/v0.1.9/language-server

**Comment by witcan** [comment]
> It looks like the NPM mirror you used is not up-to-date so `copilot-node-server-1.6.0` is not found.
> 
> * https://registry.npm.taobao.org/copilot-node-server/-/copilot-node-server-1.6.0.tgz
> * https://cdn.npmmirror.com/packages/copilot-node-server/1.6.0/copilot-node-server-1.6.0.tgz

Thanks, I tried to modify the npm source `npm config set registry https://registry.npmjs.org` , now it works fine!
