### ISSUE TITLE
ImportError: No module named 'LSP'

### ISSUE THREAD

**Issue by XbNz** [TerminalFi/LSP-copilot#83]
M1 MacBook Air
macOS: 13.2
Sublime Text: 4143

After installing LSP through package control:

```
reloading python 3.3 plugin LSP-copilot.boot
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-copilot.sublime-package/boot.py", line 12, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-copilot.sublime-package/plugin/__init__.py", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP-copilot.sublime-package/plugin/commands.py", line 5, in <module>
ImportError: No module named 'LSP'
```

No `Copilot: SIgn In` in command palette

**Comment by jfcherng** [comment]
Did you restart ST?

**Comment by XbNz** [comment]
> Did you restart ST?

Yes, multiple times. This is my second effort to install this package after I was initially unsuccessful in December.

**Comment by salzig** [comment]
Just had the same error. But LSP was already installed (for quite a while). 

Reinstalled "LSP" and "LSP-copilot", now it works.
