### ISSUE TITLE
after i install the package i dont get a Copilot: Sign In option in the console

### ISSUE THREAD

**Issue by obnoxiousish** [TerminalFi/LSP-copilot#92]
after i install the package i dont get a Copilot: Sign In option in the console

why is this? is it failing to install or something how can I check

**Comment by jfcherng** [comment]
> or something how can I check

Yes, restart ST and check step 1 in https://github.com/TerminalFi/LSP-copilot#setup

**Comment by obnoxiousish** [comment]
i have multiple times, and yes I installed both correctly unless these installation guides are missing steps....

is there an error log somewhere? I see sometimes I get a npm error

As well I removed and reinstalled package + restart ST a few times

im on manjaro kde

**Comment by jfcherng** [comment]
Run `LSP: troubleshoot server` for `LSP-copilot` and paste the output here may give some clues.

**Comment by obnoxiousish** [comment]
https://imgur.com/a/2Wc2093 does this help and running that now

**Comment by obnoxiousish** [comment]
# Troubleshooting: LSP-copilot
## Version
 - LSP: 1.23.0
 - Sublime Text: 4143
## Server Test Run
 - exit code: -1
 - output
```
Error installing the server:
Failed to run npm command "ci --omit=dev --scripts-prepend-node-path=true --verbose":
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@8.19.2
npm info using node@v19.6.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/home/joey/.cache/sublime-text/Package Storage/LSP-copilot/19.6.0/language-server/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/joey/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 5ms
npm timing npm:load:configload Completed in 5ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm ci
npm verb argv "ci" "--omit" "dev" "--scripts-prepend-node-path" "true" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 0ms
npm timing config:load:flatten Completed in 1ms
npm timing npm:load:display Completed in 3ms
npm verb logfile logs-max:10 dir:/home/joey/.npm/_logs
npm verb logfile /home/joey/.npm/_logs/2023-03-11T04_21_52_218Z-debug-0.log
npm timing npm:load:logFile Completed in 3ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 12ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 1ms
npm timing idealTree:userRequests Completed in 0ms
npm timing idealTree:#root Completed in 0ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 2ms
npm timing npm-ci:rm Completed in 0ms
npm timing reify:loadTrees Completed in 1ms
npm timing reify:diffTrees Completed in 0ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 1ms
npm timing reify:trashOmits Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm verb audit error FetchError: request to https://registry.npmjs.org/-/npm/v1/security/audits/quick failed, reason: connect ECONNREFUSED 2606:4700::6810:1923:443
npm verb audit error     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm verb audit error     at ClientRequest.emit (node:events:512:28)
npm verb audit error     at TLSSocket.socketErrorListener (node:_http_client:496:9)
npm verb audit error     at TLSSocket.emit (node:events:524:35)
npm verb audit error     at emitErrorNT (node:internal/streams/destroy:151:8)
npm verb audit error     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm verb audit error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm verb audit error  FetchError: request to https://registry.npmjs.org/-/npm/v1/security/audits/quick failed, reason: connect ECONNREFUSED 2606:4700::6810:1923:443
npm verb audit error     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm verb audit error     at ClientRequest.emit (node:events:512:28)
npm verb audit error     at TLSSocket.socketErrorListener (node:_http_client:496:9)
npm verb audit error     at TLSSocket.emit (node:events:524:35)
npm verb audit error     at emitErrorNT (node:internal/streams/destroy:151:8)
npm verb audit error     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm verb audit error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm verb audit error   code: 'ECONNREFUSED',
npm verb audit error   errno: 'ECONNREFUSED',
npm verb audit error   syscall: 'connect',
npm verb audit error   address: '2606:4700::6810:1923',
npm verb audit error   port: 443,
npm verb audit error   type: 'system'
npm verb audit error }
npm timing auditReport:getReport Completed in 2051ms
npm timing reify:audit Completed in 2052ms
npm timing reify:rollback:createSparse Completed in 3ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:ci Completed in 73161ms
npm verb type system
npm verb stack FetchError: request to https://registry.npmjs.org/copilot-node-server/-/copilot-node-server-1.8.3.tgz failed, reason: connect ECONNREFUSED 2606:4700::6810:1923:443
npm verb stack     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm verb stack     at ClientRequest.emit (node:events:512:28)
npm verb stack     at TLSSocket.socketErrorListener (node:_http_client:496:9)
npm verb stack     at TLSSocket.emit (node:events:524:35)
npm verb stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm verb stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm verb cwd /home/joey/.cache/sublime-text/Package Storage/LSP-copilot/19.6.0/language-server
npm verb Linux 6.1.12-1-MANJARO
npm verb node v19.6.0
npm verb npm  v8.19.2
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/copilot-node-server/-/copilot-node-server-1.8.3.tgz failed, reason: connect ECONNREFUSED 2606:4700::6810:1923:443
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:512:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:496:9)
npm ERR!     at TLSSocket.emit (node:events:524:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!  FetchError: request to https://registry.npmjs.org/copilot-node-server/-/copilot-node-server-1.8.3.tgz failed, reason: connect ECONNREFUSED 2606:4700::6810:1923:443
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:512:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:496:9)
npm ERR!     at TLSSocket.emit (node:events:524:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '2606:4700::6810:1923',
npm ERR!   port: 443,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm verb exit 1
npm timing npm Completed in 73210ms
npm verb unfinished npm timer reify 1678508512277
npm verb unfinished npm timer reify:unpack 1678508512284
npm verb unfinished npm timer reifyNode:node_modules/copilot-node-server 1678508512284
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joey/.npm/_logs/2023-03-11T04_21_52_218Z-debug-0.log
```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh

```
 - selector
```
source | text | embedding
```
 - priority_selector
```
source | text | embedding
```
 - init_options
```json
{}
```
 - settings
```json
{
  "auto_ask_completions": true, 
  "completion_style": "popup", 
  "debug": false, 
  "hook_to_auto_complete_command": false, 
  "local_checks": false, 
  "telemetry": false
}
```
 - env
```json
{}
```

## Active view
 - File name
```
None
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Text/Plain text.tmLanguage"
}
```
 - base scope
```
text.plain
```

## Project / Workspace
 - folders
```json
[]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - /home/joey/.local/bin
 - /usr/local/sbin
 - /usr/local/bin
 - /usr/bin
 - /home/joey/.dotnet/tools
 - /usr/bin/site_perl
 - /usr/bin/vendor_perl
 - /usr/bin/core_perl

**Comment by jfcherng** [comment]
Very helpful. It looks like your local Node.js setup failed to download a package from NPM. But I've no further thought from the error message at this moment.

**Comment by obnoxiousish** [comment]
my vpn config had ipv6 disabled reenabling it allowed it to install ok weird

**Comment by jfcherng** [comment]
So it looks like as of Node.js v17, it may use IPv6 for DNS resolution by default.
- https://github.com/nodejs/node/issues/40537
- https://github.com/npm/cli/issues/4163
- https://github.com/nodejs/node/pull/39987
And that can be an issue for downloading packages from NPM.

We can force it to use IPv4 with `--dns-result-order=ipv4first` CLI argument.

I will report this to upstream.

**Comment by jfcherng** [comment]
Closed as resolved.
